Alloy-Sample/Models/Register/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Alloy_Sample.Models
{
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "Username")]
        [RegularExpression(@"^[a-zA-Z0-9_-]+$", ErrorMessage = "Username can only contain letters a-z, numbers, underscores and hyphens.")]
        [StringLength(20, ErrorMessage ="The {0} field can not be more than {1} characters long.")]
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [AllowHtml]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        [AllowHtml]
        public string ConfirmPassword { get; set; }

    }
}

Alloy-Sample/Controllers/RegisterController.cs
using Alloy_Sample.Models;
using EPiServer.Core;
using EPiServer.ServiceLocation;
using EPiServer.Shell.Security;
using EPiServer.Web.Routing;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Profile;
using EPiServer.Security;
using EPiServer.DataAbstraction;
using EPiServer.Personalization;

namespace Alloy_Sample.Controllers
{
    /// <summary>
    /// Used to register a user for first time
    /// </summary>
    public class RegisterController : Controller
    {
        const string AdminRoleName = "WebAdmins";
        public const string ErrorKey = "CreateError";

        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Index(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                UIUserCreateStatus status;
                IEnumerable<string> errors = Enumerable.Empty<string>();
                var result = UIUserProvider.CreateUser(model.Username, model.Password, model.Email, null, null, true, out status, out errors);
                if (status == UIUserCreateStatus.Success)
                {
                    UIRoleProvider.CreateRole(AdminRoleName);
                    UIRoleProvider.AddUserToRoles(result.Username, new string[] { AdminRoleName });

                    if (ProfileManager.Enabled)
                    {
                        var profile = EPiServerProfile.Wrap(ProfileBase.Create(result.Username));
                        profile.Email = model.Email;
                        profile.Save();
                    }

                    AdministratorRegistrationPage.IsEnabled = false;
                    SetFullAccessToWebAdmin();
                    var resFromSignIn = UISignInManager.SignIn(UIUserProvider.Name, model.Username, model.Password);
                    if (resFromSignIn)
                    {
                        return Redirect(UrlResolver.Current.GetUrl(ContentReference.StartPage));
                    }
                }
                AddErrors(errors);
            }
            // If we got this far, something failed, redisplay form
            return View(model);
        }

        private void SetFullAccessToWebAdmin()
        {
            var securityrep = ServiceLocator.Current.GetInstance<IContentSecurityRepository>();
            var permissions = securityrep.Get(ContentReference.RootPage).CreateWritableClone() as IContentSecurityDescriptor;
            permissions.AddEntry(new AccessControlEntry(AdminRoleName, AccessLevel.FullAccess));
            securityrep.Save(ContentReference.RootPage, permissions, SecuritySaveType.Replace);
        }

        private void AddErrors(IEnumerable<string> errors)
        {
            foreach (var error in errors)
            {
                ModelState.AddModelError(ErrorKey, error);
            }
        }

        protected override void OnAuthorization(AuthorizationContext filterContext)
        {
            if (!AdministratorRegistrationPage.IsEnabled)
            {
                filterContext.Result = new HttpNotFoundResult();
                return;
            }
            base.OnAuthorization(filterContext);
        }

        UIUserProvider UIUserProvider
        {
            get
            {
                return ServiceLocator.Current.GetInstance<UIUserProvider>();
            }
        }
        UIRoleProvider UIRoleProvider
        {
            get
            {
                return ServiceLocator.Current.GetInstance<UIRoleProvider>();
            }
        }
        UISignInManager UISignInManager
        {
            get
            {
                return ServiceLocator.Current.GetInstance<UISignInManager>();
            }
        }

    }
}

Alloy-Sample/Views/Register/Index.cshtml
<!DOCTYPE html>

@using System.Web.Optimization
@using Alloy_Sample.Controllers
@model Alloy_Sample.Models.RegisterViewModel
@{
    Layout = "";
}

<html>
<head>
    <title>Create Administrator Account</title>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/js")
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="span12">

                <h2>Create Administrator Account</h2>

                @using (Html.BeginForm("/", "Register", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="control-group">
                        @Html.LabelFor(m => m.Username)
                        @Html.TextBoxFor(m => m.Username)
                        @Html.ValidationMessageFor(m => m.Username)
                    </div>
                    <div class="control-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email)
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                    <div class="control-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password)
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>
                    <div class="control-group">
                        @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword)
                        @Html.ValidationMessageFor(m => m.ConfirmPassword)
                    </div>
                    <div class="control-group">
                        @Html.ValidationMessage(RegisterController.ErrorKey)
                    </div>
                    <div class="control-group">
                        <input type="submit" class="" value="Register" />
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>